[build]
  publish = "."
  command = ""

[functions]
  node_bundler = "esbuild"
  # (Netlify usa Node 18/20 con fetch global. No necesitas dependencias.)

# Ruta bonita del frontend -> Function
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
